#!/bin/bash

# Copyright 2011 OpenStack Foundation
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.


if [[ -z $1 ]]; then
  BRANCH_NAME='master'
else
  BRANCH_NAME=$1
fi

SCRIPT_PATH='/opt/rackspace/rackerlabs-tools'
REPO_URL="https://github.com/rackerlabs/tools/raw/$BRANCH_NAME"

rm /etc/xensource/scripts/fix_vif_reordering_after_resize
rm /etc/xensource/scripts/prevent_vif_reordering_before_resize

mkdir -p $SCRIPT_PATH

curl -sSk $REPO_URL/fix_vif_reordering_after_resize $SCRIPT_PATH/fix_vif_reordering_after_resize
curl -sSk $REPO_URL/prevent_vif_reordering_before_resize $SCRIPT_PATH/prevent_vif_reordering_before_resize

chmod 755 -R $SCRIPT_PATH

ln -s $SCRIPT_PATH/fix_vif_reordering_after_resize /etc/xensource/scripts/fix_vif_reordering_after_resize
ln -s $SCRIPT_PATH/prevent_vif_reordering_before_resize /etc/xensource/scripts/prevent_vif_reordering_before_resize
